# Frequently changed
[updateandreboot]
garbagecan.binghamton.edu

# Test Machines
[test]
garbagecan.binghamton.edu

[commvault]
commmedia1.binghamton.edu
commmedia2.binghamton.edu
commmedia3.binghamton.edu
commmedia4.binghamton.edu
commserv-002.binghamton.edu

[linuxfleet]
banapp.binghamton.edu
banapp2.binghamton.edu
banapp3.binghamton.edu
banapp4.binghamton.edu
banapp5.binghamton.edu
banapp6.binghamton.edu
banapp7.binghamton.edu
banapp8.binghamton.edu
banappt.binghamton.edu
banappt2.binghamton.edu
banappt3.binghamton.edu
banappt4.binghamton.edu
banappt5.binghamton.edu
banappt6.binghamton.edu
banappt7.binghamton.edu
banappt8.binghamton.edu
bingdev.binghamton.edu
bingwww.binghamton.edu
bingweb.binghamton.edu
champagne.binghamton.edu
charon.cc.binghamton.edu
chemungv.cc.binghamton.edu
clio.cc.binghamton.edu
commmedia1.binghamton.edu
commmedia2.binghamton.edu
commmedia3.binghamton.edu
commmedia4.binghamton.edu
doc07.cc.binghamton.edu
elara.cc.binghamton.edu
frosty.binghamton.edu
frosty2.binghamton.edu
garbagecan.binghamton.edu
genesee.cc.binghamton.edu
jade.cc.binghamton.edu
janus.cc.binghamton.edu
mamdbdt.cc.binghamton.edu
mathmig.binghamton.edu
maxapp.cc.binghamton.edu
maxappt.cc.binghamton.edu
maxdb.cc.binghamton.edu
metis.cc.binghamton.edu
netmon03.binghamton.edu
onyx.cc.binghamton.edu
orion.binghamton.edu
otegov.cc.binghamton.edu
phoebe.cc.binghamton.edu
pinnweb.binghamton.edu
pinnwebdev.binghamton.edu
rscdb.binghamton.edu
rsctdb.binghamton.edu
sasbu.binghamton.edu
stargate.binghamton.edu
susquehanna.cc.binghamton.edu
tarvos.cc.binghamton.edu
venus.binghamton.edu
